default_language_version:
  python: python3.10

repos:
  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
    - id: black
      name: "Format code using Black"
      args: [--line-length, "100", --target-version, py39]
      stages: [commit]