FROM us-central1-docker.pkg.dev/sublime-sunspot-431116-t0/pred-package-container/package:latest

COPY ./app /app

ENV AIP_HTTP_PORT=8080
EXPOSE 8080

ENTRYPOINT [ "uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8080" ]