name: Github CI

on:
  push:
    branches:
      - "**"
  pull_request:
    types:
      - closed  

env:
  DOCKER_REGION: us-central1
  PACKAGE_VERSION: 1.0.0
  PACKAGE_DOCKER_URI: us-central1-docker.pkg.dev/sublime-sunspot-431116-t0/pred-package-container/package
  ENDPOINT_VERSION: 1.0.0
  ENDPOINT_DOCKER_URI: us-central1-docker.pkg.dev/sublime-sunspot-431116-t0/pred-api-container/endpoint

jobs:
  test_and_lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: pyproject.toml
      - name: Install Poetry
        uses: snok/install-poetry@v1
      - name: Install library
        run: poetry install
      - name: Check code style
        run: poetry run pre-commit
      - name: Run tests
        run: poetry run pytest .

  build_and_push_package_docker:
    needs: test_and_lint
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
      - name: Authenticate google
        uses: google-github-actions/auth@v2
        with:
          credentials_json: "${{ secrets.SERVICE_ACCOUNT_KEY }}"
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
      - name: Docker auth
        run: |-
          gcloud auth configure-docker ${{ env.DOCKER_REGION }}-docker.pkg.dev --quiet
      - name: Build image
        run: docker build . -f Dockerfile  \
            --tag ${{ env.PACKAGE_DOCKER_URI }}:${{ env.ENDPOINT_VERSION }} \
            --tag ${{ env.PACKAGE_DOCKER_URI }}:latest
      - name: Push image
        run: |
          docker push ${{ env.PACKAGE_DOCKER_URI }}:${{ env.ENDPOINT_VERSION }}
          docker push ${{ env.PACKAGE_DOCKER_URI }}:latest

  build_and_push_endpoint_docker:
    needs: build_and_push_package_docker
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
      - name: Authenticate google
        uses: google-github-actions/auth@v2
        with:
          credentials_json: "${{ secrets.SERVICE_ACCOUNT_KEY }}"
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
      - name: Docker auth
        run: |-
          gcloud auth configure-docker ${{ env.DOCKER_REGION }}-docker.pkg.dev --quiet
      - name: Build image
        run: docker build . -f Dockerfile.server  \
            --tag ${{ env.ENDPOINT_DOCKER_URI }}:${{ env.ENDPOINT_VERSION }} \
            --tag ${{ env.ENDPOINT_DOCKER_URI }}:latest
      - name: Push image
        run: |
          docker push ${{ env.ENDPOINT_DOCKER_URI }}:${{ env.ENDPOINT_VERSION }}
          docker push ${{ env.ENDPOINT_DOCKER_URI }}:latest