name: Github CI

on:
  - push

env:
  PACKAGE_VERSION: 1.0.0

jobs:
  test_and_lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: pyproject.toml
      - name: Install Poetry
        uses: snok/install-poetry@v1
      - name: Install library
        run: poetry install
      - name: Check code style
        run: poetry run pre-commit
      - name: Run tests
        run: poetry run pytest .

  build_and_push_docker:
    if: ${{ github.event.pull_request.merged }}
    needs: test_and_lint
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/price-model:${{ env.PACKAGE_VERSION }}
